language: python
sudo: false
python:
- '2.7'
# - '3.4'  # not supported yet due to dependency on 'fabric'

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - nvm install v6.3.0
  - npm install -g npm
  - pip install -U pip cookiecutter fabric

script:
  - ./run_test.sh

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
