{% raw %}---
- name: get the latest code
  git: repo={{ project_repo_url }} dest={{ project_path }} version={{ repo_version }} accept_hostkey=true
  become: false
  when: not vm
  tags: [always]

- name: manually create the initial virtualenv
  command: virtualenv {{ venv_path }} -p python3 creates={{ venv_path }}
  become: false
  tags: ['configure', 'deploy']

- name: install django python dependencies
  pip: requirements={{ project_path }}/{{ django_requirements_file }}  virtualenv={{ venv_path }}
  become: false
  tags: ['deploy']

- name: Install packages based on package.json.
  npm: path={{ project_path }} global=no
  become: true
  when: webpack
  tags: ['deploy']

- include: gunicorn.yml

- name: copy env configuration
  template: src=env.env.j2 dest={{ project_path }}/.env force=no
  become: false
  tags: ['configure']

- name: collect static
  django_manage: command=collectstatic app_path={{ project_path }} virtualenv={{ venv_path }}
  become: false
  tags: ['deploy']

- include: webpack.yml
  when: webpack

- name: Run database migrations
  django_manage: command=migrate app_path={{ project_path }} virtualenv={{ venv_path }}
  become: false
  tags: ['deploy']

- name: reload server
  shell: supervisorctl restart all
  become: true
  tags: ['deploy']{% endraw %}
